package orch

import (
	"fmt"
	"math/rand/v2"
	"os"
	"regexp"
	"time"
)

// crashMarkerContent is the sentinel written to output paths before agent execution (CHK-04).
// It deliberately fails all format validators: no '#' header (md), not valid JSON (jsonl/json/yaml).
const crashMarkerContent = "ORCH_CRASH_MARKER\n"

// retryInfix is the string embedded in retry task IDs (e.g., "agent_retry_1").
// Used by RetryTaskID to generate canonical retry IDs.
const retryInfix = "_retry_"

// RetryTaskID builds the canonical retry task ID for the given agent and attempt.
func RetryTaskID(agentID string, attempt int) string {
	return fmt.Sprintf("%s%s%d", agentID, retryInfix, attempt)
}

// retryTaskSuffix matches IDs generated by RetryTaskID: {agentID}_retry_{N}.
var retryTaskSuffix = regexp.MustCompile(`_retry_\d+$`)

// isRetryTask returns true if the task ID was generated by createRetryTask.
func isRetryTask(taskID string) bool {
	return retryTaskSuffix.MatchString(taskID)
}

// RetryConfig configures the retry protocol (ERR-01).
type RetryConfig struct {
	MaxRetries  int           // maximum retry attempts per agent (recommended: 2)
	BaseTimeout time.Duration // base timeout for scaled timeout calculation
}

// RetryState tracks retry attempts per agent.
// Keyed by original agent ID — retry tasks get fresh task IDs but the same agent ID.
type RetryState struct {
	attempts map[string]int
}

// NewRetryState creates an empty retry state.
func NewRetryState() *RetryState {
	return &RetryState{attempts: make(map[string]int)}
}

// CanRetry returns true if the agent has retries remaining (ERR-01).
func (rs *RetryState) CanRetry(agentID string, cfg RetryConfig) bool {
	return rs.attempts[agentID] < cfg.MaxRetries
}

// RecordAttempt increments the attempt count for an agent (ERR-02).
func (rs *RetryState) RecordAttempt(agentID string) {
	rs.attempts[agentID]++
}

// AttemptCount returns the number of attempts used for an agent.
func (rs *RetryState) AttemptCount(agentID string) int {
	return rs.attempts[agentID]
}

// ScaledTimeout computes the timeout for a retry attempt (ERR-01):
//
//	timeout(attempt) = base_timeout * (1.0 + 0.5 * attempt_number)
func ScaledTimeout(base time.Duration, attempt int) time.Duration {
	scale := 1.0 + 0.5*float64(attempt)
	return time.Duration(float64(base) * scale)
}

// RetryJitter adds random jitter to a duration: uniform [0, d/4].
func RetryJitter(d time.Duration) time.Duration {
	if d <= 0 {
		return 0
	}
	maxJitter := d / 4
	if maxJitter <= 0 {
		return d
	}
	jitter := time.Duration(rand.Int64N(int64(maxJitter)))
	return d + jitter
}

// GapTracker tracks non-critical agent failures and enforces the gap tolerance
// bound (ERR-07, ERR-08, S5).
//
// NOT thread-safe — must only be called from the dispatch loop's check() step
// (single goroutine). This is the TLA+ ApplyGap label atomicity requirement.
type GapTracker struct {
	gaps      int
	tolerance int
	agents    []string // agent IDs that contributed gaps (ERR-07 monotonic)
}

// NewGapTracker creates a tracker with the given tolerance (from Pipeline.GapTolerance).
func NewGapTracker(tolerance int) *GapTracker {
	return &GapTracker{tolerance: tolerance}
}

// IncrementAndCheck atomically increments the gap count and checks tolerance.
// Returns true if gaps >= tolerance (pipeline must abort, ERR-08).
// The agentID is recorded for audit purposes (ERR-07 monotonic accumulation).
func (gt *GapTracker) IncrementAndCheck(agentID string) (abort bool) {
	gt.gaps++
	gt.agents = append(gt.agents, agentID)
	return gt.gaps >= gt.tolerance
}

// Count returns the current gap count.
func (gt *GapTracker) Count() int {
	return gt.gaps
}

// Agents returns the list of agent IDs that contributed gaps.
func (gt *GapTracker) Agents() []string {
	return gt.agents
}

// SetGaps sets the gap count and agent list directly. Used by Resume to restore
// state from a prior session's event log (ERR-07 monotonic across sessions).
func (gt *GapTracker) SetGaps(count int, agents []string) {
	gt.gaps = count
	gt.agents = agents
}

// --- Crash Markers (CHK-04, CHK-05) ---

// WriteCrashMarker writes a crash marker file at the output path (CHK-04).
// The marker content deliberately fails all format validators. Agents replace it
// atomically on success. If the marker remains after a crash, resume detects it.
func WriteCrashMarker(outputPath string) error {
	if err := os.WriteFile(outputPath, []byte(crashMarkerContent), 0o644); err != nil {
		return fmt.Errorf("write crash marker: %w", err)
	}
	return nil
}

// IsCrashMarker checks if a file at the given path is a crash marker (CHK-05).
// Uses size check + content comparison to avoid reading large agent outputs.
func IsCrashMarker(path string) (bool, error) {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("check crash marker: %w", err)
	}
	// Crash marker is exactly len(crashMarkerContent) bytes. Skip files that are too large.
	if info.Size() != int64(len(crashMarkerContent)) {
		return false, nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("check crash marker: %w", err)
	}
	return string(data) == crashMarkerContent, nil
}

// RemoveCrashMarker removes a crash marker file (CHK-05 resume step).
func RemoveCrashMarker(path string) error {
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove crash marker: %w", err)
	}
	return nil
}
